### ISSUE TITLE
Pod Invitation Key--Fix format

### ISSUE THREAD

**Issue by OmneBonum** [OmneBonum/voting-portal#45]
Currently, the Pod Invitation Key uses the same format as the Entry Code.  This is not desirable.  The Entry Code should look unique.  The PIK can just be a long, random string of numbers.  Could we make it ten digits long? That way duplicates would be acceptably unlikely, and you don't have to check for uniqueness.

**Comment by zamanehsani** [comment]
has been satisfied.
