### ISSUE TITLE
Housekeeping Page--After Member is removed

### ISSUE THREAD

**Issue by OmneBonum** [OmneBonum/voting-portal#52]
When a Member Candidate uses their key, they appear as a Member Candidate at the bottom of the List of Members.  But, if they are 'Removed' by the F-Del, they are removed from the list.  

Currently, that same member can try to rejoin the group using the same key.  This is the wrong behavior.  

When a MemCan is 'removed,' if they try to use the key to re-enter the same group, they should get an error message about having used and invalid key, and directing them to contact their F-Del or the person who gave them the key.  

But, if the F-Del updates the key and gives it to the MemCan, they can use it to re-apply for membership in the group.

**Comment by zamanehsani** [comment]
this issue is going to be addressed by Pod Block list.
